language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - ziogiugno@github.com
    on_success: never
    on_failure: never
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: gatsby-migration